#!/usr/bin/php
<?php
chdir(dirname(__FILE__));
require_once 'vendor/autoload.php';
use com\github\tncrazvan\catpaw\tools\SharedObject;
use com\github\tncrazvan\catpaw\tools\shelltools\ControllerTools;

$so = new SharedObject(file_get_contents("config/args"),false);
$tools = ControllerTools::get($so);

if(!file_exists("config/args")){
    echo "Arguments file not found.\nStart your server to generate it then try again.\n";
    exit;
}

if(!isset($argv[1])){
    $argv[1] = "actions";
}
$action = $argv[1];
$controller = isset($argv[2])?$argv[2]:"";
$tools->action($action,$controller);