version: "3.4"

services:
  php:
    build:
      context: .
      target: cli_php
      args:
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    ports:
      # HTTP
      - target: 8080
        published: 8080
        protocol: tcp