#!/usr/bin/php
<?php
require_once __DIR__.'/vendor/autoload.php';
use MatthiasMullie\Minify;
use com\github\tncrazvan\CatPaw\Tools\Console;
use com\github\tncrazvan\CatPaw\Tools\Strings;

define("DEBUG",true);

$input=include("config/assets.php");

$output=[
    "css"=>"public/minified/minified.css",
    "js"=>"public/minified/minified.js"
];

Strings::minify($input["css"],$output["css"],!DEBUG);
echo "CSS minified in ".$output["css"]."\n";
Strings::minify($input["js"],$output["js"],!DEBUG);
echo "JS minified in ".$output["js"]."\n";