#!/usr/bin/php
<?php
require_once __DIR__.'/vendor/autoload.php';
use MatthiasMullie\Minify;
use com\github\tncrazvan\catpaw\tools\Console;
use com\github\tncrazvan\catpaw\tools\Strings;

define("DEBUG",true);

$assets=json_decode(file_get_contents(""));

Strings::minify($assets["css"]["input"],$assets["css"]["output"],!DEBUG);
echo "CSS minified in ".$assets["css"]["output"]."\n";
Strings::minify($assets["js"]["input"],$assets["js"]["output"],!DEBUG);
echo "JS minified in ".$assets["js"]["output"]."\n";
