#!/usr/bin/php
<?php
/**
 * Makes a PEM certificate based on the information located in config/certificate.php
 * @param $argv[1] Expiration date
 * @param $argv[2] Passphrase
 */
/*
    NOTE: You need to have OpenSSL installed on your system.
    This has only been tested on Linux Ubuntu 18.04 LTS.
*/
require_once __DIR__.'/vendor/autoload.php';
use com\github\tncrazvan\CatPaw\Tools\OpenSSL;

if(!isset($argv[1])) $argv[1] = 365;
if(!isset($argv[2])) $argv[2] = "";

$filename = __DIR__."/certificate.pem";

OpenSSL::mkcert(include("config/certificate.php"),$filename,intval($argv[1]),$argv[2]);
echo "\n$filename created.\n"; 
