#!/usr/bin/php
<?php
chdir(dirname(__FILE__));
require_once 'vendor/autoload.php';
use com\github\tncrazvan\catpaw\tools\Session;
use com\github\tncrazvan\catpaw\tools\Server;
if(count($argv) === 2){
    if(file_exists("config/args")){
        $argv[2] = file_get_contents("config/args");
    }else{
        $argv[2] = "config/http.php";
    }
}
Server::init($argv[2],false);
switch($argv[1]){
    case "mount":
        Session::mount();
    break;
    case "umount":
        Session::umount();
    break;
}
