#!/usr/bin/php
<?php
chdir(dirname(__FILE__));
define('AUTOLOADER','vendor/autoload.php');
require_once AUTOLOADER;
use com\github\tncrazvan\catpaw\CatPaw;

if(count($argv) === 1) $argv[1] = "config/config.php";
//dump classes
shell_exec("composer dump-autoload -o");

error_reporting(E_ALL);
set_time_limit(0);
ob_implicit_flush();
$server = new CatPaw($argv[1]);
$minifier = $server->minifier("minify --type=@type \"@filename\"","www/assets.json");
$server->setAutoloader(AUTOLOADER);
$server->listen(function() use (&$minifier){
    $minifier->minify();
},10);
