#!/usr/bin/php
<?php
error_reporting(E_ALL);
set_time_limit(0);
ob_implicit_flush();
ini_set('memory_limit','-1');
require 'vendor/autoload.php';
require './src/main.php';
use com\github\tncrazvan\catpaw\CatPaw;
use com\github\tncrazvan\catpaw\Event;

$server = new CatPaw([
    "port" => 80,
    "webRoot" => "./public",
    "asciiTable" => true,
    "bindAddress" => "127.0.0.1",
    "httpMaxBodyLength" => 1024*1024*200,   //200 MB max read paylod for http requests.
                                            //The above rule will not apply to http consumers,
                                            //http consumers have no read payload limit because they free memory with each
                                            //sequential read, which avoid memory overflow.
    "httpMtu" => 1024*1024*5, //5 MB
    "events" => [
        "http"=>Event::getHttpEvents(),
        "websocket"=>Event::getWebsocketEvents()
    ],
    "sessionName" => "_SESSION",
    "ramSession" => [
        "allow" => false,
        "size" => "1024M"
    ],
    "compress" => ["deflate"],
    "headers" => [
        "Cache-Control" => "no-store"
    ]
]);
$server->listen();
