#!/usr/bin/php
<?php
require 'vendor/autoload.php';
use com\github\tncrazvan\catpaw\CatPaw;
if(count($argv) === 1) 
    $argv[1] = "src/main.php";
error_reporting(E_ALL);
set_time_limit(0);
ob_implicit_flush();
ini_set('memory_limit','-1');
if($argv[1][0] !== '/'){
    $argv[1] = dirname(__FILE__).'/'.$argv[1];
}
chdir(dirname($argv[1]));
$server = new CatPaw($argv);
$server->listen();
